const GAME_FORMATS = [
  "future",
  "standard",
  "historic",
  "gladiator",
  "pioneer",
  "explorer",
  "modern",
  "legacy",
  "pauper",
  "vintage",
  "penny",
  "commander",
  "brawl",
  "historicbrawl",
  "alchemy",
  "paupercommander",
  "duel",
  "oldschool",
  "premodern",
] as const;
export default GAME_FORMATS;
